apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: status-controller
  namespace: sdt
subjects:
- kind: ServiceAccount
  name: status-controller
  namespace: sdt
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

